enum reminderEnum {
  LATER_TODAY = "LATER_TODAY",
  TOMORROW = "TOMORROW",
  NEXT_WEEK = "NEXT_WEEK",
  REMINDER = "REMINDER",

  DUE_TODAY = "DUE_TODAY",
  DUE_TOMORROW = "DUE_TOMORROW",
  DUE_NEXT_WEEK = "DUE_NEXT_WEEK",
  DUE_DATE = "DUE_DATE",

  REPEAT_DAILY = "REPEAT_DAILY",
  REPEAT_WEEKDAYS = "REPEAT_WEEKDAYS",
  REPEAT_WEEKLY = "REPEAT_WEEKLY",
  REPEAT_MONTHLY = "REPEAT_MONTHLY",
  REPEAT_YEARLY = "REPEAT_YEARLY",
  REPEAT = "REPEAT",
}

export default reminderEnum;
