const DateTimeEnum = {
    LATER_TODAY: "LATER_TODAY",
    TOMORROW: "TOMORROW",
    NEXT_WEEK: "NEXT_WEEK",
    REMINDER: "REMINDER",

    DUE_TODAY: "DUE_TODAY",
    DUE_TOMORROW: "DUE_TOMORROW",
    DUE_NEXT_WEEK: "DUE_NEXT_WEEK",
    DUE_DATE: "DUE_DATE"
}

export default  DateTimeEnum;